### ISSUE TITLE
Version 1.0 not compatible with Mimosa 1.x

### ISSUE THREAD

**Issue by kevin-buttercoin** [dbashford/mimosa-combine#12]
Doing a bower clean caused an error with logger not being found in Mimosa 1.x.  Upgrading to Mimosa 2.x fixed the issue, but not everyone will have that luxury.

mimosa-combine probably shouldn't update past 0.8.4 unless coupled with Mimosa 2.x

**Comment by dbashford** [comment]
I mention in the rel notes for 2.1 that all of the latest modules will not be compat with 2.0.8 and below. This was unavoidable I'm afraid.  So yeah, if you can't go to 2.1 you'll need to stay on older versions of the modules.

The upgrade path to 2.1 is fairly simple though.
