### ISSUE TITLE
Combine config issues with full paths

### ISSUE THREAD

**Issue by alextreppass** [dbashford/mimosa-combine#2]
Example Mimosa project location:

```
D:/foo
```

Trying to specify full paths:

``` javascript
folder: "D:/stylesheets/vendor"
output: "D:/stylesheets/vendor.css"
```

Gives me the following error:

```
Unable to start Mimosa for the following reason(s):
 * combine.folder entry [[ D:/foo/stylesheets/vendor ]] must resolve to a real path, resolves to [[ D:\foo\assets\D:\foo\stylesheets\vendor ]]
```

Trying relative paths to get some css outside of 'assets' folder works fine, as long as I traverse up:

``` javascript
folder:"../../stylesheets/vendor"
output:"../../stylesheets/vendor.css"
```

I realise I'm wondering outside the asset folder at this point, so it may not be supported.

**Comment by dbashford** [comment]
Snippet from README

```
folder: a string, the path to the folder to combine. Path is relative to the watch config settings.
output: a string, the path to the output file result of the combine. Path is relative to the watch config settings.
```

So ya, just not supported.  All paths in all modules are relative to something.  Which speaks to a larger feature I've had on the long-list of TODOs, which is for most paths of this sort to first resolve relatively, but to not give up until it has also attempted to resolve the absolute path.

It would be an easy patch, probably, to just this module to allow either relative or absolute.  I'll take a look.

**Comment by alextreppass** [comment]
Sorry, I think I skimmed the readme there.

Falling back to absolute paths as a general rule would make Mimosa pretty flexible, as long as those paths look like an absolute path. Kinda like how the [AMD spec handles paths as relative unless they start with / or http](http://requirejs.org/docs/api.html#config-paths) - but Mimosa could do "/" or a window-style drive letter e.g. "C:/"

**Comment by dbashford** [comment]
I'd likely make it a lot less smart than that.  Assume the path is relative to something (that I've documented), try and find it, if it doesn't find it, just try the entire path by itself.  No go there, then error.

Regardless, if only for this module, I can get this in soonish.

**Comment by hfjallemark** [comment]
It would be nice if the exclude and order arrays are relative to the 'folder' variable. For instance:

```
combine:[
  {
    exclude:  ['javascripts/vendor/require.js']
    folder:'javascripts/vendor'
    output:'javascripts/vendor.js'
    order: ['javascripts/vendor/knockout.js']
  }
]
```

Could just be:

```
combine:[
  {
    exclude:  ['require.js']
    folder:'javascripts/vendor'
    output:'javascripts/vendor.js'
    order: ['knockout.js']
  }
]
```

Since (I guess) exclude and order cannot be anything outside the actual folder specifing the full path seems redundant.

**Comment by dbashford** [comment]
That makes total sense.

So exclude and folder should be allowed to be full paths or relative to watch.sourceDir/watch.combinedDir.

Order should be allowed to be full paths or relative to folder.

Exclude should be allowed to be an actual regex , like `/\.txt/`, a string that is a full path, or a string that is relative to the folder.

That sound about right?

**Comment by hfjallemark** [comment]
Right on! Sounds excellent.

**Comment by dbashford** [comment]
So this fix is in and published to NPM as of a few minutes ago.

From the other issue...and at the risk of being repetitive...

To install the new mimosa combine, execute `mimosa mod:install mimosa-combine` and it'll go grab the latest one.  I have a bug lodged on mimosa regarding some problems people have experienced with this. I think it revolves around needing to execute sudo to execute the command screwing some things up.  If that fails, explicitly do a `mimosa mod:uninstall mimosa-combine` (using sudo if you need to) and then start up your mimosa project, which will reinstall it for you and grab the latest one when it does it.  And if that still fails to get it installed, reinstall mimosa (npm install mimosa -g) and start up your project.  I'd love to know how the module moving around goes, whether that works for you or not, and, obviously, how this issue's fix works for you.

**Comment by dbashford** [comment]
Closing this out
