### ISSUE TITLE
No file pattern support for exclude?

### ISSUE THREAD

**Issue by alextreppass** [dbashford/mimosa-combine#3]
Example structure:

```
assets
    |_stylesheets
        |_vendor
            |_style1.scss
            |_style2.scss
            |_readme.txt
```

The objective being to combine our 2 css files into public/stylesheets/vendor.css, but easily omit the 'readme.txt'.

The following works:

``` javascript
  combine:[
    {
      folder: "stylesheets/vendor"
      output: "stylesheets/vendor.css"
      exclude: ['stylesheets/vendor/readme.txt']
      order: null
    }
  ]
```

What we'd like to be able to do:

``` javascript
exclude: ['readme.txt']
```

or:

``` javascript
exclude: ['*.txt']
```

However if we do this, it won't match the file path name and the readme therefore gets merged into the resulting vendor.css.

Should this work?

I could have a go at a pull request sometime soon if it's something that should go in.

**Comment by dbashford** [comment]
Ya, from the README...

```
exclude: an array of strings, the list of files to exclude from the combine. Paths should be relative to the watch.compiledDir and should point at the compiled file. So foo.css, not foo.less. Can be left off or made null if not needed.
```

So the lack of support for that is purposeful.  Not for any other reason than I kept the support at strings.

I think what might be ideal is RegEx.  Less readable than file patterns, but more powerful.  So exclude turns into an array of RegExps.

The other excludes in mimosa modules and in mimosa core are regexes, not sure what I was thinking leaving this as an array of strings.

**Comment by dbashford** [comment]
I just pushed a new version of mimosa-combine to npm and to github with revamped documentation.  Exclude now supports 1) a string path relative to the `folder` property, 2) an absolute path, and 3) a regex, and these can be mixed and matched in the array of excludes.  

To install the new mimosa combine, execute `mimosa mod:install mimosa-combine` and it'll go grab the latest one.  I have a bug lodged on mimosa regarding some problems people have experienced with this. I think it revolves around needing to execute sudo to execute the command screwing some things up.  If that fails, explicitly do a `mimosa mod:uninstall mimosa-combine` (using sudo if you need to) and then start up your mimosa project, which will reinstall it for you and grab the latest one when it does it.  And if that still fails to get it installed, reinstall mimosa (npm install mimosa -g) and start up your project.  I'd love to know how the module moving around goes, whether that works for you or not, and, obviously, how this issue's fix works for you.

**Comment by dbashford** [comment]
Closing this out, regex support should carry the mail here.
