### ISSUE TITLE
Mimosa new project throws error

### ISSUE THREAD

**Issue by hfjallemark** [dbashford/mimosa-combine#4]
Since the combine module was added to the list of default modules it would be a good idea to add the 'stylesheets/vendor' to the directory structure (or change the default combine config) so that new users won't get this nasty error on first start:

```
Unable to start Mimosa for the following reason(s):
* combine.folder entry [[ stylesheets/vendor ]] must resolve to a real path, resolves to [[ C:\Temp\foo\assets\stylesheets\vendor ]]
```

**Comment by dbashford** [comment]
combine isn't actually a default module, but when you have it installed, `mimosa new` picks up on that, and adds it to your project.  It assumes that any modules you have installed inside Mimosa are ones you want in your project.  So it uncomments the modules config, adds combine, and adds the combine config block to the end of the mimosa-config.

But that is just background.  Your point remains.

I think the proper thing to do here is to have no default config for the combine module.  The config should be flagged as being for example purposes and not an actual default.  So the default config snippet turns into this: `combine: []` and the documentation here gets changed to provide an example config.

Attempting to provide a default for something so custom like this is probably a bad idea anyway.

**Comment by hfjallemark** [comment]
Ah ok mimosa new picks it up.

Yeah, agree that it's hard to provide meaningful defaults for something like this.

**Comment by dbashford** [comment]
Took the defaults out.  Now when you have combine installed, you'll get it in the module list, and you'll get the empty `combine:[]` array in your config, and when you start up, no combine will be performed.

From the other issues...and at the risk of being repetitive...

To install the new mimosa combine, execute `mimosa mod:install mimosa-combine` and it'll go grab the latest one.  I have a bug lodged on mimosa regarding some problems people have experienced with this. I think it revolves around needing to execute sudo to execute the command screwing some things up.  If that fails, explicitly do a `mimosa mod:uninstall mimosa-combine` (using sudo if you need to) and then start up your mimosa project, which will reinstall it for you and grab the latest one when it does it.  And if that still fails to get it installed, reinstall mimosa (npm install mimosa -g) and start up your project.  I'd love to know how the module moving around goes, whether that works for you or not, and, obviously, how this issue's fix works for you.

**Comment by dbashford** [comment]
Closing this...
