### ISSUE TITLE
dbashford/mimosa#138 not quite fixed

### ISSUE THREAD

**Issue by alextreppass** [dbashford/mimosa-combine#6]
We've just jumped from mimosa-combine 0.5.2 to 0.6.0 and while we get the warning about support for combine:[] being removed in the upcoming 0.11.0, there's also a fatal error as a result of the 'removeCombined' changes and mimosa quits:

```
mimosa-combine\config.coffee:32
      config.combine.removeCombined.enabled = false;
                                            ^
TypeError: Cannot set property 'enabled' of undefined
```

We'll move our config to the new syntax now in the meantime.

Thanks

**Comment by dbashford** [comment]
Since you updated it probably doesn't make sense to check this out, but this ought to be fixed. Thanks for reporting!
